version: 2.1

defaults: &defaults
  docker:
    - image: cimg/node:22.11
  working_directory: ~/project

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package-lock.json" }}
            - v2-dependencies-
      - run: npm ci
      - save_cache:
          key: v2-dependencies-{{ checksum "package-lock.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run lint

  typescript:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run tsc

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run build

workflows:
  build-and-test:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - typescript:
          requires:
            - install-dependencies
      - build:
          requires:
            - install-dependencies
